package pro.callWS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "smswsPortType", targetNamespace = "http://smsws/")
public interface SmswsPortType
{

	/**
	 * 
	 * @param content
	 * @param username
	 * @param alias
	 * @param msisdn
	 * @param shortcode
	 * @param params
	 * @param password
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "urn:smsRequest")
	@WebResult(targetNamespace = "http://smsws/xsd")
	@RequestWrapper(localName = "smsRequest", targetNamespace = "http://smsws/xsd", className = "pro.callWS.SmsRequest")
	@ResponseWrapper(localName = "smsRequestResponse", targetNamespace = "http://smsws/xsd", className = "pro.callWS.SmsRequestResponse")
	public String smsRequest(@WebParam(name = "username", targetNamespace = "http://smsws/xsd") String username,
			@WebParam(name = "password", targetNamespace = "http://smsws/xsd") String password,
			@WebParam(name = "msisdn", targetNamespace = "http://smsws/xsd") String msisdn,
			@WebParam(name = "content", targetNamespace = "http://smsws/xsd") String content,
			@WebParam(name = "shortcode", targetNamespace = "http://smsws/xsd") String shortcode,
			@WebParam(name = "alias", targetNamespace = "http://smsws/xsd") String alias,
			@WebParam(name = "params", targetNamespace = "http://smsws/xsd") String params);

}
