package pro.callWS;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * smsws service = new smsws();
 * SmswsPortType portType = service.getSmswsSOAP11PortHttp();
 * portType.smsRequest(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "smsws", targetNamespace = "http://smsws/", wsdlLocation = "http://125.212.226.53:7300/smsws?wsdl")
public class Smsws extends Service
{

	private final static URL SMSWS_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(pro.callWS.Smsws.class.getName());

	static
	{
		URL url = null;
		try
		{
			URL baseUrl;
			baseUrl = pro.callWS.Smsws.class.getResource(".");
			url = new URL(baseUrl, "http://125.212.226.53:7300/smsws?wsdl");
		}
		catch (MalformedURLException e)
		{
			logger.warning("Failed to create URL for the wsdl Location: 'http://125.212.226.53:7300/smsws?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SMSWS_WSDL_LOCATION = url;
	}

	public Smsws(URL wsdlLocation, QName serviceName)
	{
		super(wsdlLocation, serviceName);
	}

	public Smsws()
	{
		super(SMSWS_WSDL_LOCATION, new QName("http://smsws/", "smsws"));
	}

	/**
	 * 
	 * @return returns SmswsPortType
	 */
	@WebEndpoint(name = "smswsSOAP11port_http")
	public SmswsPortType getSmswsSOAP11PortHttp()
	{
		return super.getPort(new QName("http://smsws/", "smswsSOAP11port_http"), SmswsPortType.class);
	}

}
